apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp:v5
  namespace: bankapp:v5
  labels:
    app: bankapp:v5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bankapp:v5
  template:
    metadata:
      labels:
        app: bankapp:v5
    spec:
      containers:
      - name: bankapp:v5
        image: madhupdevops/bankapp:v5
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: bankapp:v5
              key: SPRING_DATASOURCE_URL
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: bankapp:v5
              key: SPRING_DATASOURCE_USERNAME
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: SPRING_DATASOURCE_PASSWORD
